
rs3list = [
    # core convergences
    './rstFiles/misc/BearsInOntario.rs3',
    './rstFiles/misc/BouquetsBasket.rs3',
    './rstFiles/misc/CCletterTextGenVersion.rs3',
    './rstFiles/misc/DarwinGeologist.rs3',
    './rstFiles/misc/conference(Mann).rs3',
    './rstFiles/misc/conference(Matthiessen&T).rs3',
    './rstFiles/misc/GlobalWarming.rs3',
    './rstFiles/misc/HealthInsurance.rs3',
    './rstFiles/misc/KentuckyAward.rs3',
    './rstFiles/misc/Memorex.rs3',
    './rstFiles/misc/ResourceGuide.rs3',
    './rstFiles/misc/StaffBreakfast.rs3',
    './rstFiles/misc/Syncom.rs3',
    './rstFiles/misc/TechReports.rs3',
    './rstFiles/misc/zpg.rs3',
    './rstFiles/misc/ducasse.rs3',
    './rstFiles/misc/abelen wildlife.rs3',
    './rstFiles/misc/Bateman conjunctive development.rs3',   # Bateman/Martin argumentative list
    './rstFiles/misc/President Bush insists.rs3',            # Adapted from Marcu via Das
   
##    './rstFiles/misc/requestSchema.rs3', # various precedence experiments
##    './rstFiles/misc/requestSchema2.rs3',
##    './rstFiles/misc/requestSchema3.rs3',

##    './rstFiles/misc/Avoiding chains Not OK.rs3',    # zeldes guidelines example of TBA
    
##    './rstFiles/misc/GUM_news_worship.rs3',   # zeldes conv-free version
    './rstFiles/misc/GUM_news_worship_2016.rs3',  # zeldes early convergent version
##    './rstFiles/misc/GUM_news_worship_conv.rs3', # not sure where this is from 

##  Selected Potsdam Convergences (English Translations)
    './rstFiles/maz-english/maz-11766e.rs3',    # bilaterial with listable !! Important scoping/precedence 
    './rstFiles/maz-english/maz-13758e.rs3',    # convergence within a convergence
    './rstFiles/maz-english/maz-14654e.rs3',    # bilaterial with listable + stair step
    './rstFiles/maz-english/maz-18354e.rs3',    # background summary 
    './rstFiles/maz-english/maz-18750e.rs3',    # background summary interpretation + LHS ladders
    './rstFiles/maz-english/maz-3367e.rs3',     # bilateral with listable
    './rstFiles/maz-english/maz-6918e.rs3',     # complex conv (enablement, evidence, elaboration elaboration)
##  Selected Potsdam Convergences (English Translations) scoping study
    './rstFiles/maz-english/maz-12383e.rs3',
    './rstFiles/maz-english/maz-12473e.rs3',    # Changed evaluation_e to reason (see straddlers notes)
    './rstFiles/maz-english/maz-12576e.rs3',
    './rstFiles/maz-english/maz-13125e.rs3',
    './rstFiles/maz-english/maz-15155e.rs3',
    './rstFiles/maz-english/maz-15702e.rs3',
    './rstFiles/maz-english/maz-15734e.rs3',
    './rstFiles/maz-english/maz-1757e.rs3',     # Conv., + stair step example
    './rstFiles/maz-english/maz-17698e.rs3',
    './rstFiles/maz-english/maz-18333e.rs3',    # Conv., + LHS stair step example
    './rstFiles/maz-english/maz-19012e.rs3',
    './rstFiles/maz-english/maz-6159e.rs3',

#   Some LHS Convergences
    './rstFiles/online learning/W-Web-M35-P11.rs3',  # LHS motivation enablement convergence
    './rstFiles/online learning/A-Usab-M42-P1.rs3',   # LHS convergence solutionhood volitional-cause
    './rstFiles/online learning/W-Intuit-M18-P11.rs3',  # LHS convergence solutionhood evidence

#   selected STS    
    './rstFiles/STS Corpus/STS-Nov-M133-Fuller.rs3',
    './rstFiles/STS Corpus/STS-Nov-M137-Lynch.rs3',     # interesting elaboration sequence/ladder
    './rstFiles/STS Corpus/STS-Nov-M139-Weinstein.rs3', # concession evidence
    './rstFiles/STS Corpus/STS-Nov-M143-Bailar.rs3',    # antithesis evidence
    './rstFiles/STS Corpus/STS-Nov-M144-Hess.rs3',      # motivation * 3
    './rstFiles/STS Corpus/STS-Nov-M149-Hakken.rs3',    # elaboration * 3
    './rstFiles/STS Corpus/STS-Nov-M151-Holmes.rs3',
    './rstFiles/STS Corpus/STS-Oct-M1-Hamlett.rs3',
    './rstFiles/STS Corpus/STS-Oct-M5-Bouzid.rs3',      # plus stair step example
    './rstFiles/STS Corpus/STS-Oct-M6-Lieberman.rs3',
    './rstFiles/STS Corpus/STS-Oct-M7-Eglash.rs3',      # antithesis evidence
    './rstFiles/STS Corpus/STS-Oct-M8-Miller.rs3',      # short sweet concession evidence
    './rstFiles/STS Corpus/STS-Oct-M17-Gross.rs3',      # convergence within convergence
    './rstFiles/STS Corpus/STS-Oct-M12-Fuller.rs3',     # Serial elaborations
##    
##  Convergences from the Multilingual RST Treebank
    './rstFiles/Multilingual RST Treebank/TERM30_A1.rs3',
    './rstFiles/Multilingual RST Treebank/TERM31_A1.rs3',

##  Online learning convergences
    './rstFiles/online learning/A-Intuit-M1-P11.rs3',
    './rstFiles/online learning/A-Intuit-M11-P11.rs3',
    './rstFiles/online learning/A-Intuit-M13-P25.rs3',
    './rstFiles/online learning/A-Intuit-M15-P14.rs3',
    './rstFiles/online learning/A-Intuit-M16-P22.rs3',
    './rstFiles/online learning/A-Intuit-M18-P26.rs3',
    './rstFiles/online learning/A-Intuit-M19-P29.rs3',
    './rstFiles/online learning/A-Intuit-M20-P5.rs3',
    './rstFiles/online learning/A-Intuit-M21-P20.rs3',
    './rstFiles/online learning/A-Intuit-M22-P11.rs3',
    './rstFiles/online learning/A-Intuit-M23-P13.rs3',
    './rstFiles/online learning/A-Intuit-M24-P17.rs3',
    './rstFiles/online learning/A-Intuit-M25-P23.rs3',
    './rstFiles/online learning/A-Intuit-M26-P4.rs3',
    './rstFiles/online learning/A-Intuit-M27-P19.rs3',
    './rstFiles/online learning/A-Intuit-M28-P26.rs3',
    './rstFiles/online learning/A-Intuit-M30-P10.rs3',
    './rstFiles/online learning/A-Intuit-M31-P27.rs3',
    './rstFiles/online learning/A-Intuit-M32-P29.rs3',
    './rstFiles/online learning/A-Intuit-M33-P1.rs3',
    './rstFiles/online learning/A-Intuit-M34-P6.rs3',
    './rstFiles/online learning/A-Intuit-M5-P18.rs3',
    './rstFiles/online learning/A-Intuit-M6-P15.rs3',
    './rstFiles/online learning/A-Intuit-M7-P11.rs3',
    './rstFiles/online learning/A-Intuit-M8-P22.rs3',
    './rstFiles/online learning/A-Intuit-M9-P3.rs3',
    './rstFiles/online learning/A-Usab-M1-P11.rs3',
    './rstFiles/online learning/A-Usab-M10-P2.rs3',
    './rstFiles/online learning/A-Usab-M11-P9.rs3',
    './rstFiles/online learning/A-Usab-M13-P22.rs3',
    './rstFiles/online learning/A-Usab-M19-P22.rs3',
    './rstFiles/online learning/A-Usab-M22-P16.rs3',
    './rstFiles/online learning/A-Usab-M23-P22.rs3',
    './rstFiles/online learning/A-Usab-M24-P11.rs3',
    './rstFiles/online learning/A-Usab-M25-P26.rs3',
    './rstFiles/online learning/A-Usab-M28-P20.rs3',
    './rstFiles/online learning/A-Usab-M3-P27.rs3',
    './rstFiles/online learning/A-Usab-M32-P2.rs3',
    './rstFiles/online learning/A-Usab-M38-P21.rs3',
    './rstFiles/online learning/A-Usab-M39-P23.rs3',
    './rstFiles/online learning/A-Usab-M4-P2.rs3',
    './rstFiles/online learning/A-Usab-M40-P27.rs3',
    './rstFiles/online learning/A-Usab-M41-P19.rs3',
#    './rstFiles/online learning/A-Usab-M42-P1.rs3', #See LHS Convergences
    './rstFiles/online learning/A-Usab-M43-P29.rs3',
    './rstFiles/online learning/A-Usab-M43-P29a.rs3',
    './rstFiles/online learning/A-Usab-M43-P29b.rs3',
    './rstFiles/online learning/A-Usab-M44-P4.rs3',
    './rstFiles/online learning/A-Usab-M45-P17.rs3',
    './rstFiles/online learning/A-Usab-M46-P11.rs3',
    './rstFiles/online learning/A-Usab-M47-P17.rs3',
#    './rstFiles/online learning/A-Usab-M47-P17a.rs3', # Variation
    './rstFiles/online learning/A-Usab-M48-P15.rs3',
    './rstFiles/online learning/A-Usab-M49-P26.rs3',
    './rstFiles/online learning/A-Usab-M5-P11.rs3',
    './rstFiles/online learning/A-Usab-M50-P13.rs3',
    './rstFiles/online learning/A-Usab-M51-P14.rs3',
    './rstFiles/online learning/A-Usab-M52-P10.rs3',
    './rstFiles/online learning/A-Usab-M53-P29.rs3',
    './rstFiles/online learning/A-Usab-M6-P12.rs3',
    './rstFiles/online learning/A-Usab-M7-P7.rs3',
    './rstFiles/online learning/A-Usab-M8-P11.rs3',
    './rstFiles/online learning/A-Usab-M9-P20.rs3',
    './rstFiles/online learning/A-Web-M12-P24.rs3',
    './rstFiles/online learning/A-Web-M13-P15.rs3',
    './rstFiles/online learning/A-Web-M14-P20.rs3',
    './rstFiles/online learning/A-Web-M15-P17.rs3',
    './rstFiles/online learning/A-Web-M16-P13.rs3',
    './rstFiles/online learning/A-Web-M17-P5.rs3',
    './rstFiles/online learning/A-Web-M19-P17.rs3',
    './rstFiles/online learning/A-Web-M2-P16.rs3',
    './rstFiles/online learning/A-Web-M21-P17.rs3',
    './rstFiles/online learning/A-Web-M22-P11.rs3',
    './rstFiles/online learning/A-Web-M26-P12.rs3',
    './rstFiles/online learning/A-Web-M28-P26.rs3',
    './rstFiles/online learning/A-Web-M3-P21.rs3',
    './rstFiles/online learning/A-Web-M31-P14.rs3',
    './rstFiles/online learning/A-Web-M33-P3.rs3',
    './rstFiles/online learning/A-Web-M35-P10.rs3',
    './rstFiles/online learning/A-Web-M36-P4.rs3',
    './rstFiles/online learning/A-Web-M38-P29.rs3',
    './rstFiles/online learning/A-Web-M39-P6.rs3',
    './rstFiles/online learning/A-Web-M4-P29.rs3',
    './rstFiles/online learning/A-Web-M7-P17.rs3',
    './rstFiles/online learning/A-Web-M8-P8.rs3',
    './rstFiles/online learning/W-Intuit-M1-P11.rs3',
    './rstFiles/online learning/W-Intuit-M11-P47.rs3',
    './rstFiles/online learning/W-Intuit-M13-P45.rs3',
    './rstFiles/online learning/W-Intuit-M14-P11.rs3',
    './rstFiles/online learning/W-Intuit-M15-P40.rs3',
    './rstFiles/online learning/W-Intuit-M16-P45.rs3',
#    './rstFiles/online learning/W-Intuit-M18-P11.rs3',  # See LHS Convergences
    './rstFiles/online learning/W-Intuit-M19-P46.rs3',
    './rstFiles/online learning/W-Intuit-M2-P51.rs3',
    './rstFiles/online learning/W-Intuit-M21-P33.rs3',
    './rstFiles/online learning/W-Intuit-M22-P39.rs3',
    './rstFiles/online learning/W-Intuit-M24-P11.rs3',
    './rstFiles/online learning/W-Intuit-M26-P11.rs3',
    './rstFiles/online learning/W-Intuit-M27-P35.rs3',
    './rstFiles/online learning/W-Intuit-M28-P36.rs3',
    './rstFiles/online learning/W-Intuit-M3-P34.rs3',
    './rstFiles/online learning/W-Intuit-M30-P47.rs3',
    './rstFiles/online learning/W-Intuit-M31-P42.rs3',
    './rstFiles/online learning/W-Intuit-M33-P39.rs3',
    './rstFiles/online learning/W-Intuit-M34-P41.rs3',
    './rstFiles/online learning/W-Intuit-M35-P45.rs3',
    './rstFiles/online learning/W-Intuit-M36-P50.rs3',
    './rstFiles/online learning/W-Intuit-M37-P54.rs3',
    './rstFiles/online learning/W-Intuit-M38-P37.rs3',
    './rstFiles/online learning/W-Intuit-M39-P11.rs3',
    './rstFiles/online learning/W-Intuit-M4-P37.rs3',
    './rstFiles/online learning/W-Intuit-M40-P45.rs3',
    './rstFiles/online learning/W-Intuit-M41-P37.rs3',
    './rstFiles/online learning/W-Intuit-M44-P42.rs3',
    './rstFiles/online learning/W-Intuit-M45-P45.rs3',
    './rstFiles/online learning/W-Intuit-M46-P43.rs3',
    './rstFiles/online learning/W-Intuit-M49-P45.rs3',
    './rstFiles/online learning/W-Intuit-M5-P52.rs3',
    './rstFiles/online learning/W-Intuit-M50-P47.rs3',
    './rstFiles/online learning/W-Intuit-M52-P42.rs3',
    './rstFiles/online learning/W-Intuit-M53-P48.rs3',
    './rstFiles/online learning/W-Intuit-M58-P48.rs3',
    './rstFiles/online learning/W-Intuit-M59-P30.rs3',
    './rstFiles/online learning/W-Intuit-M6-P49.rs3',
    './rstFiles/online learning/W-Intuit-M60-P53.rs3',
    './rstFiles/online learning/W-Intuit-M61-P44.rs3',
    './rstFiles/online learning/W-Intuit-M8-P49.rs3',
    './rstFiles/online learning/W-Usab-M1-P11.rs3',
    './rstFiles/online learning/W-Usab-M10-P48.rs3',
    './rstFiles/online learning/W-Usab-M12-P48.rs3',
    './rstFiles/online learning/W-Usab-M13-P39.rs3',
    './rstFiles/online learning/W-Usab-M14-P46.rs3',
    './rstFiles/online learning/W-Usab-M15-P45.rs3',
    './rstFiles/online learning/W-Usab-M17-P48.rs3',
    './rstFiles/online learning/W-Usab-M18-P49.rs3',
    './rstFiles/online learning/W-Usab-M19-P31.rs3',
    './rstFiles/online learning/W-Usab-M2-P45.rs3',
    './rstFiles/online learning/W-Usab-M21-P37.rs3',
    './rstFiles/online learning/W-Usab-M23-P40.rs3',
    './rstFiles/online learning/W-Usab-M24-P33.rs3',
    './rstFiles/online learning/W-Usab-M25-P11.rs3',
    './rstFiles/online learning/W-Usab-M26-P37.rs3',
    './rstFiles/online learning/W-Usab-M28-P52.rs3',
    './rstFiles/online learning/W-Usab-M3-P11.rs3',
    './rstFiles/online learning/W-Usab-M30-P43.rs3',
    './rstFiles/online learning/W-Usab-M31-P45.rs3',
    './rstFiles/online learning/W-Usab-M32-P39.rs3',
    './rstFiles/online learning/W-Usab-M35-P37.rs3',
    './rstFiles/online learning/W-Usab-M36-P48.rs3',
    './rstFiles/online learning/W-Usab-M38-P11.rs3',
    './rstFiles/online learning/W-Usab-M39-P40.rs3',
    './rstFiles/online learning/W-Usab-M4-P44.rs3',
    './rstFiles/online learning/W-Usab-M41-P37.rs3',
    './rstFiles/online learning/W-Usab-M43-P40.rs3',
    './rstFiles/online learning/W-Usab-M47-P35.rs3',
    './rstFiles/online learning/W-Usab-M48-P11.rs3',
    './rstFiles/online learning/W-Usab-M5-P47.rs3',
    './rstFiles/online learning/W-Usab-M50-P54.rs3',
    './rstFiles/online learning/W-Usab-M51-P39.rs3',
    './rstFiles/online learning/W-Usab-M54-P36.rs3',
    './rstFiles/online learning/W-Usab-M55-P11.rs3',
    './rstFiles/online learning/W-Usab-M56-P45.rs3',
    './rstFiles/online learning/W-Usab-M58-P54.rs3',
    './rstFiles/online learning/W-Usab-M61-P49.rs3',
    './rstFiles/online learning/W-Usab-M64-P53.rs3',
    './rstFiles/online learning/W-Usab-M66-P30.rs3',
    './rstFiles/online learning/W-Usab-M67-P48.rs3',
    './rstFiles/online learning/W-Usab-M69-P43.rs3',
    './rstFiles/online learning/W-Usab-M7-P46.rs3',
    './rstFiles/online learning/W-Usab-M70-P43.rs3',
    './rstFiles/online learning/W-Usab-M72-P48.rs3',
    './rstFiles/online learning/W-Usab-M8-P37.rs3',
    './rstFiles/online learning/W-Usab-M9-P45.rs3',
    './rstFiles/online learning/W-Web-M10-P45.rs3',
    './rstFiles/online learning/W-Web-M11-P38.rs3',
    './rstFiles/online learning/W-Web-M12-P47.rs3',
    './rstFiles/online learning/W-Web-M13-P39.rs3',
    './rstFiles/online learning/W-Web-M15-P39.rs3',
    './rstFiles/online learning/W-Web-M16-P31.rs3',
    './rstFiles/online learning/W-Web-M17-P51.rs3',
    './rstFiles/online learning/W-Web-M18-P11.rs3',
    './rstFiles/online learning/W-Web-M19-P11.rs3',
    './rstFiles/online learning/W-Web-M2-P33.rs3',
#    './rstFiles/online learning/W-Web-M2-P33a.rs3',    # ?
    './rstFiles/online learning/W-Web-M20-P33.rs3',
    './rstFiles/online learning/W-Web-M21-P43.rs3',
    './rstFiles/online learning/W-Web-M23-P45.rs3',
    './rstFiles/online learning/W-Web-M24-P40.rs3',
    './rstFiles/online learning/W-Web-M25-P46.rs3',
    './rstFiles/online learning/W-Web-M26-P37.rs3',
    './rstFiles/online learning/W-Web-M28-P38.rs3',
    './rstFiles/online learning/W-Web-M30-P45.rs3',
    './rstFiles/online learning/W-Web-M31-P39.rs3',
    './rstFiles/online learning/W-Web-M32-P37.rs3',
    './rstFiles/online learning/W-Web-M33-P39.rs3',
    './rstFiles/online learning/W-Web-M34-P47.rs3',
#    './rstFiles/online learning/W-Web-M35-P11.rs3',    # See LHS Convergences
    './rstFiles/online learning/W-Web-M36-P45.rs3',
    './rstFiles/online learning/W-Web-M38-P30.rs3',
    './rstFiles/online learning/W-Web-M4-P45.rs3',
    './rstFiles/online learning/W-Web-M40-P37.rs3',
    './rstFiles/online learning/W-Web-M43-P33.rs3',
    './rstFiles/online learning/W-Web-M45-38.rs3',
    './rstFiles/online learning/W-Web-M47-P45.rs3',
    './rstFiles/online learning/W-Web-M49-P33.rs3',
    './rstFiles/online learning/W-Web-M5 P45.rs3',
    './rstFiles/online learning/W-Web-M50-P37.rs3',
    './rstFiles/online learning/W-Web-M51-P54.rs3',
    './rstFiles/online learning/W-Web-M54-P45.rs3',
    './rstFiles/online learning/W-Web-M55-P52.rs3',
    './rstFiles/online learning/W-Web-M56-P32.rs3',
    './rstFiles/online learning/W-Web-M57-P39.rs3',
    './rstFiles/online learning/W-Web-M58-P49.rs3',
    './rstFiles/online learning/W-Web-M59-P37.rs3',
    './rstFiles/online learning/W-Web-M6-P46.rs3',
    './rstFiles/online learning/W-Web-M60-P43.rs3',
    './rstFiles/online learning/W-Web-M61-P42.rs3',
    './rstFiles/online learning/W-Web-M8 P42.rs3',
    './rstFiles/online learning/W-Web-M9-P38.rs3',

# online learning full set, including non-convergences for test purposes
##     './rstFiles/online learning complete/A-Intuit-M1-P11.rs3',
##     './rstFiles/online learning complete/A-Intuit-M10-P23.rs3',
##     './rstFiles/online learning complete/A-Intuit-M11-P11.rs3',
##     './rstFiles/online learning complete/A-Intuit-M12-P12.rs3',
##     './rstFiles/online learning complete/A-Intuit-M13-P25.rs3',
##     './rstFiles/online learning complete/A-Intuit-M14-P17.rs3',
##     './rstFiles/online learning complete/A-Intuit-M15-P14.rs3',
##     './rstFiles/online learning complete/A-Intuit-M16-P22.rs3',
##     './rstFiles/online learning complete/A-Intuit-M17-P21.rs3',
##     './rstFiles/online learning complete/A-Intuit-M18-P26.rs3',
##     './rstFiles/online learning complete/A-Intuit-M19-P29.rs3',
##     './rstFiles/online learning complete/A-Intuit-M2-P24.rs3',
##     './rstFiles/online learning complete/A-Intuit-M20-P5.rs3',
##     './rstFiles/online learning complete/A-Intuit-M21-P20.rs3',
##     './rstFiles/online learning complete/A-Intuit-M22-P11.rs3',
##     './rstFiles/online learning complete/A-Intuit-M23-P13.rs3',
##     './rstFiles/online learning complete/A-Intuit-M24-P17.rs3',
##     './rstFiles/online learning complete/A-Intuit-M25-P23.rs3',
##     './rstFiles/online learning complete/A-Intuit-M26-P4.rs3',
##     './rstFiles/online learning complete/A-Intuit-M27-P19.rs3',
##     './rstFiles/online learning complete/A-Intuit-M28-P26.rs3',
##     './rstFiles/online learning complete/A-Intuit-M29-P16.rs3',
##     './rstFiles/online learning complete/A-Intuit-M3-P12.rs3',
##     './rstFiles/online learning complete/A-Intuit-M30-P10.rs3',
##     './rstFiles/online learning complete/A-Intuit-M31-P27.rs3',
##     './rstFiles/online learning complete/A-Intuit-M32-P29.rs3',
##     './rstFiles/online learning complete/A-Intuit-M33-P1.rs3',
##     './rstFiles/online learning complete/A-Intuit-M34-P6.rs3',
##     './rstFiles/online learning complete/A-Intuit-M35-P8.rs3',
##     './rstFiles/online learning complete/A-Intuit-M4-P9.rs3',
##     './rstFiles/online learning complete/A-Intuit-M5-P18.rs3',
##     './rstFiles/online learning complete/A-Intuit-M6-P15.rs3',
##     './rstFiles/online learning complete/A-Intuit-M7-P11.rs3',
##     './rstFiles/online learning complete/A-Intuit-M8-P22.rs3',
##     './rstFiles/online learning complete/A-Intuit-M9-P3.rs3',
##     './rstFiles/online learning complete/A-Usab-M1-P11.rs3',
##     './rstFiles/online learning complete/A-Usab-M10-P2.rs3',
##     './rstFiles/online learning complete/A-Usab-M11-P9.rs3',
##     './rstFiles/online learning complete/A-Usab-M12-P24.rs3',
##     './rstFiles/online learning complete/A-Usab-M13-P22.rs3',
##     './rstFiles/online learning complete/A-Usab-M14-P4.rs3',
##     './rstFiles/online learning complete/A-Usab-M15-P28.rs3',
##     './rstFiles/online learning complete/A-Usab-M16-P9.rs3',
##     './rstFiles/online learning complete/A-Usab-M17-P18.rs3',
##     './rstFiles/online learning complete/A-Usab-M18-P7.rs3',
##     './rstFiles/online learning complete/A-Usab-M19-P22.rs3',
##     './rstFiles/online learning complete/A-Usab-M2-P12.rs3',
##     './rstFiles/online learning complete/A-Usab-M20-P17.rs3',
##     './rstFiles/online learning complete/A-Usab-M21-P28.rs3',
##     './rstFiles/online learning complete/A-Usab-M22-P16.rs3',
##     './rstFiles/online learning complete/A-Usab-M23-P22.rs3',
##     './rstFiles/online learning complete/A-Usab-M24-P11.rs3',
##     './rstFiles/online learning complete/A-Usab-M25-P26.rs3',
##     './rstFiles/online learning complete/A-Usab-M26-P11.rs3',
##     './rstFiles/online learning complete/A-Usab-M27-P2.rs3',
##     './rstFiles/online learning complete/A-Usab-M28-P20.rs3',
##     './rstFiles/online learning complete/A-Usab-M29-P11.rs3',
##     './rstFiles/online learning complete/A-Usab-M3-P27.rs3',
##     './rstFiles/online learning complete/A-Usab-M30-P12.rs3',
##     './rstFiles/online learning complete/A-Usab-M31-P11.rs3',
##     './rstFiles/online learning complete/A-Usab-M32-P2.rs3',
##     './rstFiles/online learning complete/A-Usab-M33 P5.rs3',
##     './rstFiles/online learning complete/A-Usab-M34-P7.rs3',
##     './rstFiles/online learning complete/A-Usab-M35-P19.rs3',
##     './rstFiles/online learning complete/A-Usab-M36-P2.rs3',
##     './rstFiles/online learning complete/A-Usab-M37-P12.rs3',
##     './rstFiles/online learning complete/A-Usab-M38-P21.rs3',
##     './rstFiles/online learning complete/A-Usab-M39-P23.rs3',
##     './rstFiles/online learning complete/A-Usab-M4-P2.rs3',
##     './rstFiles/online learning complete/A-Usab-M40-P27.rs3',
##     './rstFiles/online learning complete/A-Usab-M41-P19.rs3',
##     './rstFiles/online learning complete/A-Usab-M42-P1.rs3',
##     './rstFiles/online learning complete/A-Usab-M43-P29.rs3',
##     './rstFiles/online learning complete/A-Usab-M43-P29a.rs3',
##     './rstFiles/online learning complete/A-Usab-M43-P29b.rs3',
##     './rstFiles/online learning complete/A-Usab-M44-P4.rs3',
##     './rstFiles/online learning complete/A-Usab-M45-P17.rs3',
##     './rstFiles/online learning complete/A-Usab-M46-P11.rs3',
##     './rstFiles/online learning complete/A-Usab-M47-P17.rs3',
####     './rstFiles/online learning complete/A-Usab-M47-P17a.rs3', # Variation
##     './rstFiles/online learning complete/A-Usab-M48-P15.rs3',
##     './rstFiles/online learning complete/A-Usab-M49-P26.rs3',
##     './rstFiles/online learning complete/A-Usab-M5-P11.rs3',
##     './rstFiles/online learning complete/A-Usab-M50-P13.rs3',
##     './rstFiles/online learning complete/A-Usab-M51-P14.rs3',
##     './rstFiles/online learning complete/A-Usab-M52-P10.rs3',
##     './rstFiles/online learning complete/A-Usab-M53-P29.rs3',
##     './rstFiles/online learning complete/A-Usab-M6-P12.rs3',
##     './rstFiles/online learning complete/A-Usab-M7-P7.rs3',
##     './rstFiles/online learning complete/A-Usab-M8-P11.rs3',
##     './rstFiles/online learning complete/A-Usab-M9-P20.rs3',
##     './rstFiles/online learning complete/A-Web-M1-P11.rs3',
##     './rstFiles/online learning complete/A-Web-M10-P7.rs3',
##     './rstFiles/online learning complete/A-Web-M11-P11.rs3',
##     './rstFiles/online learning complete/A-Web-M12-P24.rs3',
##     './rstFiles/online learning complete/A-Web-M13-P15.rs3',
##     './rstFiles/online learning complete/A-Web-M14-P20.rs3',
##     './rstFiles/online learning complete/A-Web-M15-P17.rs3',
##     './rstFiles/online learning complete/A-Web-M16-P13.rs3',
##     './rstFiles/online learning complete/A-Web-M17-P5.rs3',
##     './rstFiles/online learning complete/A-Web-M18-P17.rs3',   
##     './rstFiles/online learning complete/A-Web-M19-P17.rs3',
##     './rstFiles/online learning complete/A-Web-M2-P16.rs3',
##     './rstFiles/online learning complete/A-Web-M20-P11.rs3',
##     './rstFiles/online learning complete/A-Web-M21-P17.rs3',
##     './rstFiles/online learning complete/A-Web-M22-P11.rs3',
##     './rstFiles/online learning complete/A-Web-M23-P25.rs3',
##     './rstFiles/online learning complete/A-Web-M24-P26.rs3',
##     './rstFiles/online learning complete/A-Web-M25-P19.rs3',
##     './rstFiles/online learning complete/A-Web-M26-P12.rs3',
##     './rstFiles/online learning complete/A-Web-M27-P1.rs3',
##     './rstFiles/online learning complete/A-Web-M28-P26.rs3',
###     './rstFiles/online learning complete/A-Web-M29-P12.rs3',   # span only
##     './rstFiles/online learning complete/A-Web-M3-P21.rs3',
##     './rstFiles/online learning complete/A-Web-M30-P28.rs3',
##     './rstFiles/online learning complete/A-Web-M31-P14.rs3',
##     './rstFiles/online learning complete/A-Web-M32-P4.rs3',
##     './rstFiles/online learning complete/A-Web-M33-P3.rs3',
##     './rstFiles/online learning complete/A-Web-M34-P28.rs3',
##     './rstFiles/online learning complete/A-Web-M35-P10.rs3',
##     './rstFiles/online learning complete/A-Web-M36-P4.rs3',
###     './rstFiles/online learning complete/A-Web-M37-P9.rs3',    # span only
##     './rstFiles/online learning complete/A-Web-M38-P29.rs3',
##     './rstFiles/online learning complete/A-Web-M39-P6.rs3',
##     './rstFiles/online learning complete/A-Web-M4-P29.rs3',
##     './rstFiles/online learning complete/A-Web-M5-P22.rs3',
##     './rstFiles/online learning complete/A-Web-M6-P18.rs3',
##     './rstFiles/online learning complete/A-Web-M7-P17.rs3',
##     './rstFiles/online learning complete/A-Web-M8-P8.rs3',
##     './rstFiles/online learning complete/A-Web-M9-P16.rs3',
##     './rstFiles/online learning complete/W-Intuit-M1-P11.rs3',
###     './rstFiles/online learning complete/W-Intuit-M10-P11.rs3',    # span only
##     './rstFiles/online learning complete/W-Intuit-M11-P47.rs3',
##     './rstFiles/online learning complete/W-Intuit-M12-P11.rs3',
##     './rstFiles/online learning complete/W-Intuit-M13-P45.rs3',
##     './rstFiles/online learning complete/W-Intuit-M14-P11.rs3',
##     './rstFiles/online learning complete/W-Intuit-M15-P40.rs3',
##     './rstFiles/online learning complete/W-Intuit-M16-P45.rs3',
##     './rstFiles/online learning complete/W-Intuit-M17-P37.rs3',
##     './rstFiles/online learning complete/W-Intuit-M18-P11.rs3',
##     './rstFiles/online learning complete/W-Intuit-M19-P46.rs3',
##     './rstFiles/online learning complete/W-Intuit-M2-P51.rs3',
##     './rstFiles/online learning complete/W-Intuit-M20-P11.rs3',
##     './rstFiles/online learning complete/W-Intuit-M21-P33.rs3',
##     './rstFiles/online learning complete/W-Intuit-M22-P39.rs3',
##     './rstFiles/online learning complete/W-Intuit-M23-P39.rs3',
##     './rstFiles/online learning complete/W-Intuit-M24-P11.rs3',
##     './rstFiles/online learning complete/W-Intuit-M25-P39.rs3',
##     './rstFiles/online learning complete/W-Intuit-M26-P11.rs3',
##     './rstFiles/online learning complete/W-Intuit-M27-P35.rs3',
##     './rstFiles/online learning complete/W-Intuit-M28-P36.rs3',
##     './rstFiles/online learning complete/W-Intuit-M29-P11.rs3',
##     './rstFiles/online learning complete/W-Intuit-M3-P34.rs3',
##     './rstFiles/online learning complete/W-Intuit-M30-P47.rs3',
##     './rstFiles/online learning complete/W-Intuit-M31-P42.rs3',
##     './rstFiles/online learning complete/W-Intuit-M32-P11.rs3',
##     './rstFiles/online learning complete/W-Intuit-M33-P39.rs3',
##     './rstFiles/online learning complete/W-Intuit-M34-P41.rs3',
##     './rstFiles/online learning complete/W-Intuit-M35-P45.rs3',
##     './rstFiles/online learning complete/W-Intuit-M36-P50.rs3',
##     './rstFiles/online learning complete/W-Intuit-M37-P54.rs3',
##     './rstFiles/online learning complete/W-Intuit-M38-P37.rs3',
##     './rstFiles/online learning complete/W-Intuit-M39-P11.rs3',
##     './rstFiles/online learning complete/W-Intuit-M4-P37.rs3',
##     './rstFiles/online learning complete/W-Intuit-M40-P45.rs3',
##     './rstFiles/online learning complete/W-Intuit-M41-P37.rs3',
##     './rstFiles/online learning complete/W-Intuit-M42-P45.rs3',
##     './rstFiles/online learning complete/W-Intuit-M43-P11.rs3',
##     './rstFiles/online learning complete/W-Intuit-M44-P42.rs3',
##     './rstFiles/online learning complete/W-Intuit-M45-P45.rs3',
##     './rstFiles/online learning complete/W-Intuit-M46-P43.rs3',
##     './rstFiles/online learning complete/W-Intuit-M47-P46.rs3',
##     './rstFiles/online learning complete/W-Intuit-M48-P39.rs3',
##     './rstFiles/online learning complete/W-Intuit-M49-P45.rs3',
##     './rstFiles/online learning complete/W-Intuit-M5-P52.rs3',
##     './rstFiles/online learning complete/W-Intuit-M50-P47.rs3',
##     './rstFiles/online learning complete/W-Intuit-M51-P39.rs3',
##     './rstFiles/online learning complete/W-Intuit-M52-P42.rs3',
##     './rstFiles/online learning complete/W-Intuit-M53-P48.rs3',
###     './rstFiles/online learning complete/W-Intuit-M54-P11.rs3', # span only
##     './rstFiles/online learning complete/W-Intuit-M55-P30.rs3',
##     './rstFiles/online learning complete/W-Intuit-M56-P37.rs3',
##     './rstFiles/online learning complete/W-Intuit-M57-P45.rs3',
##     './rstFiles/online learning complete/W-Intuit-M58-P48.rs3',
##     './rstFiles/online learning complete/W-Intuit-M59-P30.rs3',
##     './rstFiles/online learning complete/W-Intuit-M6-P49.rs3',
##     './rstFiles/online learning complete/W-Intuit-M60-P53.rs3',
##     './rstFiles/online learning complete/W-Intuit-M61-P44.rs3',
##     './rstFiles/online learning complete/W-Intuit-M7-P42.rs3',
##     './rstFiles/online learning complete/W-Intuit-M8-P49.rs3',
##     './rstFiles/online learning complete/W-Intuit-M9-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M1-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M10-P48.rs3',
##     './rstFiles/online learning complete/W-Usab-M11-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M12-P48.rs3',
##    './rstFiles/online learning complete/W-Usab-M13-P39.rs3', # WTF? recursion error, reedited
##     './rstFiles/online learning complete/W-Usab-M14-P46.rs3',
##     './rstFiles/online learning complete/W-Usab-M15-P45.rs3',
##     './rstFiles/online learning complete/W-Usab-M16-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M17-P48.rs3',
##     './rstFiles/online learning complete/W-Usab-M18-P49.rs3',
##     './rstFiles/online learning complete/W-Usab-M19-P31.rs3',
##     './rstFiles/online learning complete/W-Usab-M2-P45.rs3',
###     './rstFiles/online learning complete/W-Usab-M20-P11.rs3',   # span only
##     './rstFiles/online learning complete/W-Usab-M21-P37.rs3',
##     './rstFiles/online learning complete/W-Usab-M22-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M23-P40.rs3',
##     './rstFiles/online learning complete/W-Usab-M24-P33.rs3',
##     './rstFiles/online learning complete/W-Usab-M25-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M26-P37.rs3',
###     './rstFiles/online learning complete/W-Usab-M27-P11.rs3',   # span only
##     './rstFiles/online learning complete/W-Usab-M28-P52.rs3',
##     './rstFiles/online learning complete/W-Usab-M29-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M3-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M30-P43.rs3',
##     './rstFiles/online learning complete/W-Usab-M31-P45.rs3',
##     './rstFiles/online learning complete/W-Usab-M32-P39.rs3',
##     './rstFiles/online learning complete/W-Usab-M33-P43.rs3',
##     './rstFiles/online learning complete/W-Usab-M34-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M35-P37.rs3',
##     './rstFiles/online learning complete/W-Usab-M36-P48.rs3',
##     './rstFiles/online learning complete/W-Usab-M37-P50.rs3',
##     './rstFiles/online learning complete/W-Usab-M38-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M39-P40.rs3',
##     './rstFiles/online learning complete/W-Usab-M4-P44.rs3',
##     './rstFiles/online learning complete/W-Usab-M40-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M41-P37.rs3',
###     './rstFiles/online learning complete/W-Usab-M42-P37.rs3', # span only
##     './rstFiles/online learning complete/W-Usab-M43-P40.rs3',
###     './rstFiles/online learning complete/W-Usab-M44-P30.rs3', # span only
###     './rstFiles/online learning complete/W-Usab-M45-P30.rs3', # span only
##     './rstFiles/online learning complete/W-Usab-M46-P40.rs3',
##     './rstFiles/online learning complete/W-Usab-M47-P35.rs3',
##     './rstFiles/online learning complete/W-Usab-M48-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M49-P37.rs3',
##     './rstFiles/online learning complete/W-Usab-M5-P47.rs3',
##     './rstFiles/online learning complete/W-Usab-M50-P54.rs3',
##     './rstFiles/online learning complete/W-Usab-M51-P39.rs3',
##     './rstFiles/online learning complete/W-Usab-M52-P47.rs3',
##     './rstFiles/online learning complete/W-Usab-M53-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M54-P36.rs3',
##     './rstFiles/online learning complete/W-Usab-M55-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M56-P45.rs3',
##     './rstFiles/online learning complete/W-Usab-M57-P11.rs3',   # WTF recursion error, reedited
##     './rstFiles/online learning complete/W-Usab-M58-P54.rs3',
##     './rstFiles/online learning complete/W-Usab-M59-P11.rs3',
###     './rstFiles/online learning complete/W-Usab-M6-P11.rs3',   # span only
##     './rstFiles/online learning complete/W-Usab-M60-P48.rs3',
##     './rstFiles/online learning complete/W-Usab-M61-P49.rs3',
##     './rstFiles/online learning complete/W-Usab-M62-P11.rs3',
###     './rstFiles/online learning complete/W-Usab-M63-P11.rs3',   # span only
##     './rstFiles/online learning complete/W-Usab-M64-P53.rs3',
##     './rstFiles/online learning complete/W-Usab-M65-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M66-P30.rs3',
##     './rstFiles/online learning complete/W-Usab-M67-P48.rs3',
##     './rstFiles/online learning complete/W-Usab-M68-P43.rs3',
##     './rstFiles/online learning complete/W-Usab-M69-P43.rs3',
##     './rstFiles/online learning complete/W-Usab-M7-P46.rs3',
##     './rstFiles/online learning complete/W-Usab-M70-P43.rs3',
##     './rstFiles/online learning complete/W-Usab-M71-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M72-P48.rs3',
##     './rstFiles/online learning complete/W-Usab-M73-P11.rs3',
##     './rstFiles/online learning complete/W-Usab-M8-P37.rs3',
##     './rstFiles/online learning complete/W-Usab-M9-P45.rs3',
##     './rstFiles/online learning complete/W-Web-M1-P11.rs3',
##     './rstFiles/online learning complete/W-Web-M10-P45.rs3',
##     './rstFiles/online learning complete/W-Web-M11-P38.rs3',
##     './rstFiles/online learning complete/W-Web-M12-P47.rs3',
##     './rstFiles/online learning complete/W-Web-M13-P39.rs3',
##     './rstFiles/online learning complete/W-Web-M14-P46.rs3',
##     './rstFiles/online learning complete/W-Web-M15-P39.rs3',
##     './rstFiles/online learning complete/W-Web-M16-P31.rs3',
##     './rstFiles/online learning complete/W-Web-M17-P51.rs3',
##     './rstFiles/online learning complete/W-Web-M18-P11.rs3',
##     './rstFiles/online learning complete/W-Web-M19-P11.rs3',
##     './rstFiles/online learning complete/W-Web-M2-P33.rs3',
##     './rstFiles/online learning complete/W-Web-M2-P33a.rs3',
##     './rstFiles/online learning complete/W-Web-M20-P33.rs3',
##     './rstFiles/online learning complete/W-Web-M21-P43.rs3',
###     './rstFiles/online learning complete/W-Web-M22-P11.rs3',    # span only
##     './rstFiles/online learning complete/W-Web-M23-P45.rs3',
##     './rstFiles/online learning complete/W-Web-M24-P40.rs3',
##     './rstFiles/online learning complete/W-Web-M25-P46.rs3',
##     './rstFiles/online learning complete/W-Web-M26-P37.rs3',
##     './rstFiles/online learning complete/W-Web-M27-P11.rs3',
##     './rstFiles/online learning complete/W-Web-M28-P38.rs3',
##     './rstFiles/online learning complete/W-Web-M29-P36.rs3',
##     './rstFiles/online learning complete/W-Web-M3-P46.rs3',
##     './rstFiles/online learning complete/W-Web-M30-P45.rs3',
##     './rstFiles/online learning complete/W-Web-M31-P39.rs3',
##     './rstFiles/online learning complete/W-Web-M32-P37.rs3',
##     './rstFiles/online learning complete/W-Web-M33-P39.rs3',
##     './rstFiles/online learning complete/W-Web-M34-P47.rs3',
##     './rstFiles/online learning complete/W-Web-M35-P11.rs3',
##     './rstFiles/online learning complete/W-Web-M36-P45.rs3',
##     './rstFiles/online learning complete/W-Web-M37-P39.rs3',
##     './rstFiles/online learning complete/W-Web-M38-P30.rs3',
##     './rstFiles/online learning complete/W-Web-M39-P32.rs3',
##     './rstFiles/online learning complete/W-Web-M4-P45.rs3',
##     './rstFiles/online learning complete/W-Web-M40-P37.rs3',
##     './rstFiles/online learning complete/W-Web-M41-P11.rs3',
##     './rstFiles/online learning complete/W-Web-M42-P11.rs3',
##     './rstFiles/online learning complete/W-Web-M43-P33.rs3',
##     './rstFiles/online learning complete/W-Web-M44-P11.rs3',
##     './rstFiles/online learning complete/W-Web-M45-38.rs3',
##     './rstFiles/online learning complete/W-Web-M46-P50.rs3',
##     './rstFiles/online learning complete/W-Web-M47-P45.rs3',
###     './rstFiles/online learning complete/W-Web-M48-P11.rs3',   # span only
##     './rstFiles/online learning complete/W-Web-M49-P33.rs3',
##     './rstFiles/online learning complete/W-Web-M5 P45.rs3',
##     './rstFiles/online learning complete/W-Web-M50-P37.rs3',
##     './rstFiles/online learning complete/W-Web-M51-P54.rs3',
##     './rstFiles/online learning complete/W-Web-M52-P11.rs3',
##     './rstFiles/online learning complete/W-Web-M53-P49.rs3',
##     './rstFiles/online learning complete/W-Web-M54-P45.rs3',
##     './rstFiles/online learning complete/W-Web-M55-P52.rs3',
##     './rstFiles/online learning complete/W-Web-M56-P32.rs3',
##     './rstFiles/online learning complete/W-Web-M57-P39.rs3',
##     './rstFiles/online learning complete/W-Web-M58-P49.rs3',
##     './rstFiles/online learning complete/W-Web-M59-P37.rs3',
##     './rstFiles/online learning complete/W-Web-M6-P46.rs3',
##     './rstFiles/online learning complete/W-Web-M60-P43.rs3',
##     './rstFiles/online learning complete/W-Web-M61-P42.rs3',
##     './rstFiles/online learning complete/W-Web-M62-P46.rs3',
##     './rstFiles/online learning complete/W-Web-M7-P11.rs3',
##     './rstFiles/online learning complete/W-Web-M8 P42.rs3',
##     './rstFiles/online learning complete/W-Web-M9-P38.rs3',

    # not the full potsdam, just the convergences
    # and some few of these present features unique for this study.
    # See above MAZ links for selected translated versions
    
##    './rstFiles/potsdamRST/maz-00001.rs3',# bilateral interpretation interpretation
##    './rstFiles/potsdamRST/maz-00002.rs3', # bilateral interpretation interpretation
##    './rstFiles/potsdamRST/maz-11299.rs3', # bilateral  background interpreation
##    './rstFiles/potsdamRST/maz-11670.rs3', # bilateral background interpretation
##    './rstFiles/potsdamRST/maz-11735.rs3',  # bilaterial evaluation-s evaluation-s
###    './rstFiles/potsdamRST/maz-11766.rs3',  # bilaterial with listable
##    './rstFiles/potsdamRST/maz-11916.rs3', # bilaterial evidence evidence
##    './rstFiles/potsdamRST/maz-12188.rs3', # listable
##    './rstFiles/potsdamRST/maz-12383.rs3', # bilaterial  antitjesis reason
##    './rstFiles/potsdamRST/maz-12473.rs3',  # bilaterial evaluation reason
##    './rstFiles/potsdamRST/maz-12576.rs3', # bilaterial antithesis reason REVIEW THIS 
##    './rstFiles/potsdamRST/maz-12666.rs3',  # bilaterial  reason elaboration
##    './rstFiles/potsdamRST/maz-13125.rs3',  # bilaterial evidence reason
###    './rstFiles/potsdamRST/maz-13758.rs3',   # convergence within a convergence
##    './rstFiles/potsdamRST/maz-13915.rs3',  # bilaterial background interpretation interpreation
##    './rstFiles/potsdamRST/maz-14047.rs3',  # bilaterial background interpretation
##    './rstFiles/potsdamRST/maz-14055.rs3',  # bilaterial preparation e-elaboration
##    './rstFiles/potsdamRST/maz-14590.rs3',  # bilaterial  reason interpretation
###    './rstFiles/potsdamRST/maz-14654.rs3', # bilaterial with listable, but...
##    './rstFiles/potsdamRST/maz-14853.rs3',  # bilaterial background result
##    './rstFiles/potsdamRST/maz-14881.rs3', # bilaterial  interpretation result
##    './rstFiles/potsdamRST/maz-15155.rs3', # bilaterial interpretation interpretation
##    './rstFiles/potsdamRST/maz-15609.rs3', # bilaterial reason reason
##    './rstFiles/potsdamRST/maz-15702.rs3', # bilaterial reason reason
##    './rstFiles/potsdamRST/maz-15734.rs3',# bilaterial  reason reason
##    './rstFiles/potsdamRST/maz-15970.rs3', # bilaterial  background reason
##    './rstFiles/potsdamRST/maz-16153.rs3', # bilaterial preparation reason
##    './rstFiles/potsdamRST/maz-16177.rs3', # bilaterial background interpretation
##    './rstFiles/potsdamRST/maz-16987.rs3',# bilaterial  interpretation e-elaboration
##    './rstFiles/potsdamRST/maz-17539.rs3', # bilaterial circumstance interpretation
##    './rstFiles/potsdamRST/maz-1757.rs3', # bilaterial reason reason
##    './rstFiles/potsdamRST/maz-17698.rs3', # bilaterial reason reason
##    './rstFiles/potsdamRST/maz-18333.rs3', # bilaterial interpretation interpretation
###    './rstFiles/potsdamRST/maz-18354.rs3', # background summary 
###   './rstFiles/potsdamRST/maz-18750.rs3', # background summary interpretation
##    './rstFiles/potsdamRST/maz-19012.rs3', # bilaterial evidence evidence
##    './rstFiles/potsdamRST/maz-19372.rs3', # bilaterial reason interpretation
##    './rstFiles/potsdamRST/maz-19436.rs3',
##    './rstFiles/potsdamRST/maz-2609.rs3', # bilaterial solutionhood evidence
##    './rstFiles/potsdamRST/maz-2669.rs3', # bilaterial background evaluation-s
###    './rstFiles/potsdamRST/maz-3367.rs3',   # bilateral with listability
##    './rstFiles/potsdamRST/maz-4031.rs3', 
##    './rstFiles/potsdamRST/maz-4403.rs3', # bilaterial circumstance evaluation-s
##    './rstFiles/potsdamRST/maz-4472.rs3', # bilaterial background reason concession
##    './rstFiles/potsdamRST/maz-5007.rs3', # bilaterial solutionhood elaboration
##    './rstFiles/potsdamRST/maz-5012.rs3', # bilaterial evidence interpretion
##    './rstFiles/potsdamRST/maz-5873.rs3', # bilaterial cause elaboration-s
##    './rstFiles/potsdamRST/maz-6046.rs3', # bilaterial Background interpretation
##    './rstFiles/potsdamRST/maz-6159.rs3',
##    './rstFiles/potsdamRST/maz-6165.rs3',
##    './rstFiles/potsdamRST/maz-6728.rs3',
###    './rstFiles/potsdamRST/maz-6918.rs3', # # complex conv (enablement, evidence, elaboration elaboration)
##    './rstFiles/potsdamRST/maz-6993.rs3', # bilaterial circumstance interpretation
##    './rstFiles/potsdamRST/maz-7690.rs3', # bilateral reason evaluation-s
##    './rstFiles/potsdamRST/maz-7967.rs3', # bilateral Background evaluation-s
##    './rstFiles/potsdamRST/maz-8288.rs3', # bilateral Background evaluation-s
##    './rstFiles/potsdamRST/maz-8361.rs3', # bilateral Interpretation Reason
##    './rstFiles/potsdamRST/maz-8509.rs3', # bilateral Reason Restatement
##    './rstFiles/potsdamRST/maz-8563.rs3', # bilateral Concession Restatement
##    './rstFiles/potsdamRST/maz-8665.rs3', # bilateral Evaluation-n Evidence
##    './rstFiles/potsdamRST/maz-8981.rs3', # bilateral background Evidence
##    './rstFiles/potsdamRST/maz-9207.rs3', # bilateral reason evidence
##    './rstFiles/potsdamRST/maz-9335.rs3',
##    './rstFiles/potsdamRST/maz-9538.rs3', # bilateral circumstance cause
##    './rstFiles/potsdamRST/maz-9884.rs3',
##    './rstFiles/potsdamRST/maz-9891.rs3',

## STS Corpus complete including nonconvergences
##     './rstFiles/STS Corpus Complete/STS-Nov-M133-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M134-Herkert.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M134a-Hakken.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M135-Traweek.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M136-Lynch.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M137-Lynch.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M138-Hess.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M139-Weinstein.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M140-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M141-Durbin.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M143-Bailar.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M144-Hess.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M145-Edwards.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M146-La Porte.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M147-Schmaus.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M148-Lynch.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M149-Hakken.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M150-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M151-Holmes.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M152-Shapiro.rs3',
##     './rstFiles/STS Corpus Complete/STS-Nov-M153-Hess.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M1-Hamlett.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M10-Collins.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M100-Reid.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M101-Gale.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M102-Maisel.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M103-Hineline.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M104-Traweek.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M105-Schmaus.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M106-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M107-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M108-Edwards.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M109-Martin.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M11-Morman.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M110-Heath.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M111-Frost.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M112-Turton.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M113-Hauger.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M114-Morman.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M115-Herkert.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M116-Eglash.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M117-Marks.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M118-Schmaus.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M119-Frost.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M12-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M120-Schmaus.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M121-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M122-Frost.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M123-Turton.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M124-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M125-Marks.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M126-Marks.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M127-Turton.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M128-Guston.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M129-Lynch.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M13-Lee.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M130-Lynch.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M131-La Porte.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M132-Heath.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M15-Dennis.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M16-Bouzid.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M17-Gross.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M18-Edwards.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M18a-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M19-Lieberman.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M2-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M20-Collins.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M21-Lee.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M22-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M23-Hamlett.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M24-Bouzid.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M25-Hofman.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M26-Weiss.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M27-Gross.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M28-Leydesdorff.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M29-Morman.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M3-Busch.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M30-Marks.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M31-Gross.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M32-Turney.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M34-Eglash.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M35-Timmermans.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M36-Frost.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M38-Frost.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M39-Eglash.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M4-Morman.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M40-Hakken.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M41-Gross.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M42-Shanks.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M43-Richardson.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M44-Richardson.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M45-Bromley.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M46-Lieberman.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M47-Dunlap.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M48-Guston.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M49-Schmaus.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M5-Bouzid.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M50-Collins.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M51-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M52-Richardson.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M53-Phillipson.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M54-Shanks.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M56-Gale.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M57-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M58-Gale.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M59-Shanks.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M6-Lieberman.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M60-Shanks.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M61-Soyland.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M62-Bailar.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M63-Felker.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M64-Hardcastle.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M65-Marks.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M66-Hineline.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M67-van der Meulen.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M68-Kaloudis.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M69-Edwards.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M7-Eglash.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M70-Gross.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M71-Keith.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M72-Gross.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M73-Leydesdorff.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M74-Edwards.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M75-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M76-Hakken.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M77-Gale.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M78-Croissant.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M79-Bailar.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M8-Miller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M80-Bailar.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M81-Taylor.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M82-van der Meulen.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M83-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M84-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M85-Hakken.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M86-Soyland.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M87-Schmaus.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M89-Hofmann.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M9-Baxter.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M90-Traweek.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M91-Anguelov.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M92-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M93-Heath.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M94-Phillipson.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M94a-Stockdale.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M95-Eglash.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M96-Traweek.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M97-Fuller.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M98-Marks.rs3',
##     './rstFiles/STS Corpus Complete/STS-Oct-M99-Bailar.rs3',
     ]





